### ISSUE TITLE
大佬你好，出现没有找到红球模型错误，怎么解决？谢谢，是64位的win电脑不行吗？

### ISSUE THREAD

**Issue by Mengmake** [KittenCN/predict_Lottery_ticket_pytorch#12]
2024-06-28 16:11:10.578 | INFO     | __main__:<module>:522 - 正在创建【快乐8】数据集...
2024-06-28 16:11:11.004 | INFO     | common:get_data_run:122 - 【快乐8】最新一期期号：2024169
2024-06-28 16:11:11.004 | INFO     | common:get_data_run:123 - 正在获取【快乐8】数据。。。
2024-06-28 16:11:13.910 | INFO     | common:get_data_run:131 - 【快乐8】数据准备就绪，共910期, 下一步可训练模型...
2024-06-28 16:11:13.910 | INFO     | __main__:action:447 - 正在创建【快乐8】数据集...
100%|████████████████████████████████████████████████████████████████████████████████| 866/866 [00:28<00:00, 30.38it/s]
2024-06-28 16:11:42.447 | INFO     | common:create_train_data:112 - 红球训练集数据维度: (866, 6, 80)
100%|██████████████████████████████████████████████████████████████████████████████████| 34/34 [00:01<00:00, 33.53it/s]
2024-06-28 16:11:43.461 | INFO     | common:create_train_data:112 - 红球测试集数据维度: (34, 6, 80)
2024-06-28 16:11:43.461 | INFO     | __main__:action:486 - 开始训练【快乐8】红球模型...
2024-06-28 16:11:43.461 | INFO     | __main__:train_ball_model:197 - 标签数据维度: (866, 6, 80)
2024-06-28 16:11:44.916 | INFO     | __main__:train_ball_model:246 - 系统将尝试读取最后版本继续训练！
2024-06-28 16:11:44.916 | INFO     | __main__:load_model:179 - 没有找到红球模型，将重新训练！
2024-06-28 16:11:44.916 | INFO     | __main__:train_ball_model:288 - 当前epoch是 0, 初次启动时间是 20240628161110, 最佳分数是 1.00e+09, 最佳损失是 1.00e+09
  0%|                                                                                          | 0/100 [00:00<?, ?it/s]Traceback (most recent call last):
  File "run_train_model.py", line 564, in <module>
    run(args.name, list_windows_size)
  File "run_train_model.py", line 511, in run
    action(name)
  File "run_train_model.py", line 488, in action
    train_ball_model(name, dataset=red_train_data, test_dataset=red_test_data, sub_name="红球")
  File "run_train_model.py", line 313, in train_ball_model
    for batch in dataloader:
  File "C:\Users\Administrator\anaconda3\envs\pytorch\lib\site-packages\prefetch_generator\__init__.py", line 116, in next
    raise next_item
  File "C:\Users\Administrator\anaconda3\envs\pytorch\lib\site-packages\prefetch_generator\__init__.py", line 98, in run    for item in self.generator: self.queue.put((True , item))
  File "C:\Users\Administrator\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "C:\Users\Administrator\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\Administrator\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Administrator\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Administrator\Downloads\predict_Lottery_ticket_pytorch-master\modeling.py", line 490, in __getitem__
    x_hot = binary_encode_array(x, self.num_classes)
  File "C:\Users\Administrator\Downloads\predict_Lottery_ticket_pytorch-master\modeling.py", line 38, in binary_encode_array
    binary_encoded_array[i, number - 1] = 1.0  # Adjust index for 0-based indexing
IndexError: tensors used as indices must be long, int, byte or bool tensors
  0%|                                                                                          | 0/100 [00:00<?, ?it/s]

(pytorch) C:\Users\Administrator\Downloads\predict_Lottery_ticket_pytorch-master>

**Comment by zytops** [comment]
可能是启动参数没配置对。

**Comment by zhongliIOS** [comment]
解决了吗，我也出现了这个问题

**Comment by liujunling721** [comment]
modeling.py文件36行改为number = int(input_array[i, j].item())，然后run_train_model.py文件42行，default默认为LSTM

**Comment by leoy1111s** [comment]
请指导一下，这是什么问题。
(ssqycgx) C:\cs\predict_Lottery_ticket_pytorch-master>python get_data.py --name ssq
2024-12-18 09:06:18.010 | INFO     | common:get_data_run:122 - 【双色球】最新一期期号：24145
2024-12-18 09:06:18.012 | INFO     | common:get_data_run:123 - 正在获取【双色球】数据。。。
2024-12-18 09:06:21.085 | INFO     | common:get_data_run:131 - 【双色球】数据准备就绪，共3240期, 下一步可训练模型...

(ssqycgx) C:\cs\predict_Lottery_ticket_pytorch-master>python run_train_model.py --name ssq
2024-12-18 09:06:28.535 | INFO     | __main__:<module>:522 - 正在创建【双色球】数据集...
2024-12-18 09:06:29.414 | INFO     | common:get_data_run:122 - 【双色球】最新一期期号：24145
2024-12-18 09:06:29.414 | INFO     | common:get_data_run:123 - 正在获取【双色球】数据。。。
2024-12-18 09:06:32.485 | INFO     | common:get_data_run:131 - 【双色球】数据准备就绪，共3240期, 下一步可训练模型...
2024-12-18 09:06:32.485 | INFO     | __main__:action:447 - 正在创建【双色球】数据集...
2024-12-18 09:06:32.501 | ERROR    | common:create_train_data:76 -  请执行 get_data.py 进行数据下载！
Traceback (most recent call last):
  File "run_train_model.py", line 564, in <module>
    run(args.name, list_windows_size)
  File "run_train_model.py", line 511, in run
    action(name)
  File "run_train_model.py", line 468, in action
    red_train_data = create_train_data(name=args.name, windows=model_args[name]["model_args"]["windows_size"],
  File "C:\cs\predict_Lottery_ticket_pytorch-master\common.py", line 76, in create_train_data
    raise logger.error(" 请执行 get_data.py 进行数据下载！")
TypeError: exceptions must derive from BaseException

**Comment by leoy1111s** [comment]
> modeling.py文件36行改为number = int(input_array[i, j].item())，然后run_train_model.py文件42行，default默认为LSTM

文件修改后，出现新问题，请指教。
  File "run_train_model.py", line 564, in <module>
    run(args.name, list_windows_size)
  File "run_train_model.py", line 511, in run
    action(name)
  File "run_train_model.py", line 488, in action
    train_ball_model(name, dataset=red_train_data, test_dataset=red_test_data, sub_name="红球")
  File "run_train_model.py", line 321, in train_ball_model
    y_pred = model(x).view(-1, m_args["model_args"]["{}_sequence_len".format(sub_name_eng)],
RuntimeError: shape '[-1, 20, 80]' is invalid for input of size 80
  0%|
