### ISSUE TITLE
IndexError: tensors used as indices must be long, int, byte or bool tensors

### ISSUE THREAD

**Issue by haoyuandz** [KittenCN/predict_Lottery_ticket_pytorch#13]

**Comment by leoy1111s** [comment]
大佬，指导一下这是什么原因？
(ssqycgx) C:\cs\predict_Lottery_ticket_pytorch-master>python get_data.py --name ssq
2024-12-18 09:06:18.010 | INFO     | common:get_data_run:122 - 【双色球】最新一期期号：24145
2024-12-18 09:06:18.012 | INFO     | common:get_data_run:123 - 正在获取【双色球】数据。。。
2024-12-18 09:06:21.085 | INFO     | common:get_data_run:131 - 【双色球】数据准备就绪，共3240期, 下一步可训练模型...

(ssqycgx) C:\cs\predict_Lottery_ticket_pytorch-master>python run_train_model.py --name ssq
2024-12-18 09:06:28.535 | INFO     | __main__:<module>:522 - 正在创建【双色球】数据集...
2024-12-18 09:06:29.414 | INFO     | common:get_data_run:122 - 【双色球】最新一期期号：24145
2024-12-18 09:06:29.414 | INFO     | common:get_data_run:123 - 正在获取【双色球】数据。。。
2024-12-18 09:06:32.485 | INFO     | common:get_data_run:131 - 【双色球】数据准备就绪，共3240期, 下一步可训练模型...
2024-12-18 09:06:32.485 | INFO     | __main__:action:447 - 正在创建【双色球】数据集...
2024-12-18 09:06:32.501 | ERROR    | common:create_train_data:76 -  请执行 get_data.py 进行数据下载！
Traceback (most recent call last):
  File "run_train_model.py", line 564, in <module>
    run(args.name, list_windows_size)
  File "run_train_model.py", line 511, in run
    action(name)
  File "run_train_model.py", line 468, in action
    red_train_data = create_train_data(name=args.name, windows=model_args[name]["model_args"]["windows_size"],
  File "C:\cs\predict_Lottery_ticket_pytorch-master\common.py", line 76, in create_train_data
    raise logger.error(" 请执行 get_data.py 进行数据下载！")
TypeError: exceptions must derive from BaseException
