### ISSUE TITLE
M3芯片运行到训练命令出错

### ISSUE THREAD

**Issue by lby1994** [KittenCN/predict_Lottery_ticket_pytorch#5]
(lby)  ✘  cpTest/cpNew  python get_data.py  --name ssq
2024-04-16 16:27:16.313 | INFO     | common:get_data_run:115 - 【双色球】最新一期期号：24041
2024-04-16 16:27:16.313 | INFO     | common:get_data_run:116 - 正在获取【双色球】数据。。。
2024-04-16 16:27:17.617 | INFO     | common:get_data_run:124 - 【双色球】数据准备就绪，共3136期, 下一步可训练模型...
(lby)  cpTest/cpNew  python run_train_model.py --name ssq  --windows_size 3,5,7 --red_epochs 1 --blue_epochs 1 --batch_size 1

2024-04-16 16:27:20.753 | INFO     | __main__:<module>:318 - 正在创建【双色球】数据集...
2024-04-16 16:27:21.089 | INFO     | common:get_data_run:115 - 【双色球】最新一期期号：24041
2024-04-16 16:27:21.089 | INFO     | common:get_data_run:116 - 正在获取【双色球】数据。。。
2024-04-16 16:27:22.375 | INFO     | common:get_data_run:124 - 【双色球】数据准备就绪，共3136期, 下一步可训练模型...
2024-04-16 16:27:22.375 | INFO     | __main__:action:275 - 正在创建【双色球】数据集...
2024-04-16 16:27:22.378 | INFO     | common:create_train_data:105 - 红球训练集数据维度: (339, 4, 6)
2024-04-16 16:27:22.383 | INFO     | common:create_train_data:105 - 红球测试集数据维度: (2791, 4, 6)
2024-04-16 16:27:22.384 | INFO     | common:create_train_data:105 - 蓝球训练集数据维度: (339, 4, 6)
2024-04-16 16:27:22.390 | INFO     | common:create_train_data:105 - 蓝球测试集数据维度: (2791, 4, 6)
2024-04-16 16:27:22.390 | INFO     | __main__:action:283 - 开始训练【双色球】红球模型...
2024-04-16 16:27:22.390 | INFO     | __main__:train_ball_model:130 - 标签数据维度: (339, 4, 6)
2024-04-16 16:27:22.688 | INFO     | __main__:train_ball_model:158 - 系统将尝试读取最后版本继续训练！
2024-04-16 16:27:22.688 | INFO     | __main__:load_model:113 - 没有找到红球模型，将重新训练！
2024-04-16 16:27:22.688 | INFO     | __main__:train_ball_model:167 - 当前epoch是 0, 初次启动时间是 20240416162720, 最佳分数是 1.00e+09
  0%|                                                                                                                           | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "run_train_model.py", line 360, in <module>
    run(args.name, list_windows_size)
  File "run_train_model.py", line 307, in run
    action(name)
  File "run_train_model.py", line 285, in action
    train_ball_model(name, dataset=red_train_data, test_dataset=red_test_data, sub_name="红球")
  File "run_train_model.py", line 193, in train_ball_model
    y_pred = model(x)
  File "/opt/anaconda3/envs/lby/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/lby/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/libingyuan/Desktop/cpTest/cpNew/modeling.py", line 176, in forward
    positional_encoded = self.positional_encoding(embedded)
  File "/opt/anaconda3/envs/lby/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/lby/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/libingyuan/Desktop/cpTest/cpNew/modeling.py", line 153, in forward
    x = x + self.pe[:x.size(0), :]
RuntimeError: The size of tensor a (240) must match the size of tensor b (118) at non-singleton dimension 0
  0%|                                                                                                                           | 0/1 [00:11<?, ?it/s]

**Comment by KittenCN** [comment]
没有适配Apple的M系列，目前只有X86的CPU或者Nvidia的GPU能正常运行

**Comment by lby1994** [comment]
回去换了win电脑，也是报这个错误。我尝试更换了一些库的版本，orch.cuda.is_available()返回也是true，但是还是会报这个问题

**Comment by KittenCN** [comment]
刚发现，你在搞双色球。。这个版本目前只支持快乐8.双色球也还没去适配

**Comment by lby1994** [comment]
> 刚发现，你在搞双色球。。这个版本目前只支持快乐8.双色球也还没去适配

好吧，期待大佬的更新。顺便想问一下，这个版本跟上个版本比，是某些场景（效率、成功率等）会有提升吗？

**Comment by KittenCN** [comment]
> > 刚发现，你在搞双色球。。这个版本目前只支持快乐8.双色球也还没去适配
> 
> 好吧，期待大佬的更新。顺便想问一下，这个版本跟上个版本比，是某些场景（效率、成功率等）会有提升吗？

效率是有提升，但是成功率没法比较，训练集一定是很好看的，测试集现在有办法做的比较好看，但是也只是相对于数学概率而言比较好看而已，如果你在意成功率，建议使用统计学的方法会更有效。
