### ISSUE TITLE
大神，这个代码使用Python哪个版本？为什么跑双色球，训练模型时总要求重新加载数据（之前已经加载了数据）？

### ISSUE THREAD

**Issue by platum0** [KittenCN/predict_Lottery_ticket_pytorch#8]

**Comment by KittenCN** [comment]
把完整的提升拿出来看看

**Comment by platum0** [comment]
C:\Users\Administrator\predict_Lottery_ticket_pytorch-cus_loss\Scripts\python.exe D:\workSsb\predict_Lottery_ticket_pytorch-cus_loss\run_train_model.py --name ssq --download_data 0 
2024-05-03 18:49:26.398 | INFO     | __main__:action:351 - 正在创建【双色球】数据集...
2024-05-03 18:49:26.445 | ERROR    | common:create_train_data:76 -  请执行 get_data.py 进行数据下载！
Traceback (most recent call last):
  File "D:\workSsb\predict_Lottery_ticket_pytorch-cus_loss\run_train_model.py", line 449, in <module>
    run(args.name, list_windows_size)
  File "D:\workSsb\predict_Lottery_ticket_pytorch-cus_loss\run_train_model.py", line 396, in run
    action(name)
  File "D:\workSsb\predict_Lottery_ticket_pytorch-cus_loss\run_train_model.py", line 363, in action
    red_train_data = create_train_data(name=args.name, windows=model_args[name]["model_args"]["windows_size"], dataset=1, ball_type="red", cq=args.cq, test_flag=0, test_begin=args.split_time, f_data=0, model=args.model, num_classes=model_args[name]["model_args"]["red_n_class"], test_list=test_list)
  File "D:\workSsb\predict_Lottery_ticket_pytorch-cus_loss\common.py", line 76, in create_train_data
    raise logger.error(" 请执行 get_data.py 进行数据下载！")
TypeError: exceptions must derive from BaseException

Process finished with exit code 1

**Comment by KittenCN** [comment]
双色球 啊。这个目前被我又调整了，目前只能跑快乐8
